title: Faizan A. khan
logo: /assets/img/headshot_circle2.png
description: Data scientist and AI enthusiast turning data into impactful insights with machine learning and analytics.
show_downloads: true 
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag 
google_site_verification: "nE-yBDoWCj5TcTXXNcRBPPiJZxpC6pw5dEdeRo6kTCk"
email: fayzank19@gmail.com
