title: Faizan A. khan
logo: /assets/img/headshot_circle2.png  


description: Data scientist and AI enthusiast leveraging machine learning and analytics to drive impactful solutions.
show_downloads: false 
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag 
google_site_verification: "nE-yBDoWCj5TcTXXNcRBPPiJZxpC6pw5dEdeRo6kTCk"
email: fayzank19@gmail.com
